In [1]:
import os
import pandas as pd

# Listar arquivos na pasta raw
print("Arquivos na pasta raw:")
print(os.listdir("../data/raw"))

# Definir caminho absoluto
caminho_absoluto1 = os.path.abspath("../data/raw/nafld1.csv")
caminho_absoluto2 = os.path.abspath("../data/raw/nafld2.csv")

print(f"Caminho absoluto para nafld1.csv: {caminho_absoluto1}")
print(f"Caminho absoluto para nafld2.csv: {caminho_absoluto2}")

# Carregar dados brutos usando caminho absoluto
df1 = pd.read_csv(caminho_absoluto1)
df2 = pd.read_csv(caminho_absoluto2)

# Exibir os primeiros registros dos dados
print("NAFLD1:")
display(df1.head())

print("NAFLD2:")
display(df2.head())

Arquivos na pasta raw:
['nafld1.csv', 'nafld2.csv']
Caminho absoluto para nafld1.csv: d:\jesui\Documents\projeto-mlops\data\raw\nafld1.csv
Caminho absoluto para nafld2.csv: d:\jesui\Documents\projeto-mlops\data\raw\nafld2.csv
NAFLD1:

,Unnamed: 0,id,age,male,weight,height,bmi,case.id,futime,status
0,3631,1,57,0,60.0,163.0,22.690939,10630.0,6261,0
1,8458,2,67,0,70.4,168.0,24.884028,14817.0,624,0
2,6298,3,53,1,105.8,186.0,30.453537,3.0,1783,0
3,15398,4,56,1,109.3,170.0,37.830100,6628.0,3143,0
4,13261,5,68,1,NaN,NaN,NaN,1871.0,1836,1

NAFLD2:

   Unnamed: 0  id  days  test  value
0      135077   1  -459   hdl   75.0
1      313143   1  -459  chol   75.0
2      135078   1   183   hdl   64.0
3      313144   1   183  chol   64.0
4      135079   1  2030   hdl   74.0

In [2]:
# Exibir informações gerais sobre os dados
print("\nInformações sobre NAFLD1:")
df1.info()

print("\nInformações sobre NAFLD2:")
df2.info()

# Estatísticas descritivas dos dados
print("\nEstatísticas descritivas de NAFLD1:")
display(df1.describe())

print("\nEstatísticas descritivas de NAFLD2:")
display(df2.describe())

# Verificar valores ausentes
print("\nValores ausentes em NAFLD1:")
print(df1.isnull().sum())

print("\nValores ausentes em NAFLD2:")
print(df2.isnull().sum())

Informações sobre NAFLD1:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17549 entries, 0 to 17548
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  17549 non-null  int64
 1   id          17549 non-null  int64
 2   age         17549 non-null  int64
 3   male        17549 non-null  int64
 4   weight      12763 non-null  float64
 5   height      14381 non-null  float64
 6   bmi         12588 non-null  float64
 7   case.id     17518 non-null  float64
 8   futime      17549 non-null  int64
 9   status      17549 non-null  int64
dtypes: float64(4), int64(6)
memory usage: 1.3 MB

Informações sobre NAFLD2:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400123 entries, 0 to 400122
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  400123 non-null  int64
 1   id          400123 non-null  int64
 2   days        400123 non-null  int64
 3   test        400123 non-null  object
 4   value       400123 non-null  float64
dtypes: float64(1), int64(3), object(1)
memory usage: 15.3+ MB

Estatísticas descritivas de NAFLD1:

,Unnamed: 0,id,age,male,weight,height,bmi,case.id,futime,status
count,17549.000000,17549.000000,17549.000000,17549.000000,12763.000000,14381.000000,12588.000000,17518.000000,17549.000000,17549.000000
mean,8780.106046,8784.215967,52.659639,0.467320,86.353350,169.434949,30.073865,8840.924478,2410.600547,0.077725
std,5070.539328,5070.970712,14.722515,0.498945,22.239458,10.141421,7.085435,5051.334075,1573.017638,0.267746
min,1.000000,1.000000,18.000000,0.000000,33.400000,123.000000,9.207332,3.000000,7.000000,0.000000
25%,4389.000000,4393.000000,42.000000,0.000000,70.000000,162.000000,25.136434,4598.000000,1132.000000,0.000000
50%,8778.000000,8786.000000,53.000000,0.000000,83.900000,169.000000,28.875884,8781.000000,2148.000000,0.000000
75%,13171.000000,13175.000000,63.000000,1.000000,99.200000,177.000000,33.710372,13249.000000,3353.000000,0.000000
max,17566.000000,17566.000000,98.000000,1.000000,181.700000,215.000000,84.395725,17563.000000,7268.000000,1.000000

Estatísticas descritivas de NAFLD2:

          Unnamed: 0             id           days          value
count  400123.000000  400123.000000  400123.000000  400123.000000
mean   223150.240971    8799.153905    -606.916616      63.768339
std    127822.738489    5080.553294    2415.953135      48.455567
min         1.000000       1.000000   -7651.000000       0.000000
25%    113131.500000    4410.500000   -2259.000000      40.000000
50%    222978.000000    8813.000000    -530.000000      51.000000
75%    334078.500000   13159.000000     987.000000      72.000000
max    444423.000000   17566.000000    7187.000000   13682.000000

Valores ausentes em NAFLD1:
Unnamed: 0       0
id               0
age              0
male             0
weight        4786
height        3168
bmi           4961
case.id         31
futime           0
status           0
dtype: int64

Valores ausentes em NAFLD2:
Unnamed: 0    0
id            0
days          0
test          0
value         0
dtype: int64