In [1]:
import pandas as pd

# Caminho relativo a partir do diretório do notebook
bronze_path = '../data/bronze/'
df1 = pd.read_csv(f'{bronze_path}nafld1.csv')
df2 = pd.read_csv(f'{bronze_path}nafld2.csv')

# Exibição inicial dos dados
print("NAFLD1:")
display(df1.head())

print("NAFLD2:")
display(df2.head())

# Verificação da estrutura das colunas
print("Colunas NAFLD1:", df1.columns)
print("Colunas NAFLD2:", df2.columns)

# Junção dos DataFrames
df_merged = pd.concat([df1, df2], axis=0, ignore_index=True)

# Exibição dos dados mesclados
print("DataFrame Mesclado:")
display(df_merged.head())

# Tratamento de valores ausentes (exemplo)
df_merged.fillna(method='ffill', inplace=True)

# Salvando o DataFrame como Parquet na camada Silver
silver_path = '../data/silver/'
df_merged.to_parquet(f'{silver_path}nafld_merged.parquet', engine='pyarrow')

print("Transformação concluída e arquivo salvo na camada Silver como Parquet.")

NAFLD1:

,Unnamed: 0,id,age,male,weight,height,bmi,case.id,futime,status
0,3631,1,57,0,60.0,163.0,22.690939,10630.0,6261,0
1,8458,2,67,0,70.4,168.0,24.884028,14817.0,624,0
2,6298,3,53,1,105.8,186.0,30.453537,3.0,1783,0
3,15398,4,56,1,109.3,170.0,37.830100,6628.0,3143,0
4,13261,5,68,1,NaN,NaN,NaN,1871.0,1836,1

NAFLD2:

   Unnamed: 0  id  days  test  value
0      135077   1  -459   hdl   75.0
1      313143   1  -459  chol   75.0
2      135078   1   183   hdl   64.0
3      313144   1   183  chol   64.0
4      135079   1  2030   hdl   74.0

Colunas NAFLD1: Index(['Unnamed: 0', 'id', 'age', 'male', 'weight', 'height', 'bmi', 'case.id',
       'futime', 'status'],
      dtype='object')
Colunas NAFLD2: Index(['Unnamed: 0', 'id', 'days', 'test', 'value'], dtype='object')
DataFrame Mesclado:

,Unnamed: 0,id,age,male,weight,height,bmi,case.id,futime,status,days,test,value
0,3631,1,57.0,0.0,60.0,163.0,22.690939,10630.0,6261.0,0.0,NaN,NaN,NaN
1,8458,2,67.0,0.0,70.4,168.0,24.884028,14817.0,624.0,0.0,NaN,NaN,NaN
2,6298,3,53.0,1.0,105.8,186.0,30.453537,3.0,1783.0,0.0,NaN,NaN,NaN
3,15398,4,56.0,1.0,109.3,170.0,37.830100,6628.0,3143.0,0.0,NaN,NaN,NaN
4,13261,5,68.0,1.0,NaN,NaN,NaN,1871.0,1836.0,1.0,NaN,NaN,NaN

C:\Users\jesui\AppData\Local\Temp\ipykernel_5068\2024487835.py:27: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_merged.fillna(method='ffill', inplace=True)

Transformação concluída e arquivo salvo na camada Silver como Parquet.